export type SiteLocale = "es" | "en";

export const defaultSiteLocale: SiteLocale = "es";
export const siteLocales: SiteLocale[] = ["es", "en"];

export function isSiteLocale(value: string): value is SiteLocale {
  return siteLocales.includes(value as SiteLocale);
}

const siteTexts = {
  es: {
    metadata: {
      title: "Dinerance",
      description: "Panel de Dinerance",
      htmlLang: "es",
    },
    common: {
      loading: "Cargando...",
      unexpectedError: "Error inesperado",
      none: "Ninguno",
      all: "Todos",
      clearFilters: "Limpiar filtros",
      refresh: "Actualizar",
      cancel: "Cancelar",
      saveChanges: "Guardar cambios",
      edit: "Editar",
      delete: "Eliminar",
      actions: "Acciones",
      direction: "Direccion",
      category: "Categoria",
      date: "Fecha",
      amount: "Monto",
      currency: "Moneda",
      description: "Descripcion",
      dash: "-",
      income: "Ingreso",
      expense: "Gasto",
    },
    appLayout: {
      nav: {
        balance: "Balance",
        transactions: "Transacciones",
        categories: "Categorias",
        profile: "Perfil",
      },
      signOut: "Cerrar sesion",
    },
    auth: {
      login: {
        title: "Iniciar sesion",
        email: "Correo",
        password: "Contrasena",
        submit: "Iniciar sesion",
        submitting: "Iniciando sesion...",
        noAccount: "No tienes cuenta?",
        register: "Registrate",
        notRegistered: "El usuario no esta registrado.",
        validations: {
          invalidEmail: "Correo invalido",
          passwordRequired: "La contrasena es obligatoria",
        },
        successToast: "Sesion iniciada correctamente",
      },
      register: {
        title: "Crear cuenta",
        name: "Nombre",
        email: "Correo",
        password: "Contrasena",
        confirmPassword: "Confirmar contrasena",
        submit: "Crear cuenta",
        submitting: "Creando cuenta...",
        hasAccount: "Ya tienes cuenta?",
        signIn: "Inicia sesion",
        validations: {
          nameRequired: "El nombre es obligatorio",
          invalidEmail: "Correo invalido",
          passwordMin: "La contrasena debe tener al menos 8 caracteres",
          confirmRequired: "Confirma tu contrasena",
          passwordsDontMatch: "Las contrasenas no coinciden",
        },
        successToast: "Cuenta creada correctamente.",
        profileCreatedToast: "Usuario creado correctamente.",
      },
    },
    pages: {
      balance: {
        title: "Balance",
        subtitle: "Resumen financiero del mes seleccionado y su historico.",
        heading: (monthLabel: string) => `Resumen financiero - ${monthLabel}`,
        monthLabel: "Mes",
        latestMonthHint:
          "Si no eliges un mes, se muestra el ultimo mes con movimientos.",
        currentCardDescription:
          "Vista consolidada de ingresos, gastos y balance.",
        historyTitle: "Balance mensual",
        historyDescription: "Todos los meses con movimientos registrados.",
        noHistory: "Todavia no hay movimientos para calcular el balance.",
        selectedMonthEmpty: "No hay movimientos en el mes seleccionado.",
      },
      categories: {
        title: "Categorias",
        subtitle: "Organiza tus transacciones por ingresos y gastos.",
        newCardTitle: "Nueva categoria",
        newCardDescription:
          "Agrega una categoria para agrupar tus movimientos.",
        name: "Nombre",
        direction: "Direccion",
        parentOptional: "Categoria padre (opcional)",
        namePlaceholder: "Ej: Mercado",
        create: "Crear categoria",
        creating: "Creando...",
        filters: "Filtros",
        listTitle: "Categorias",
        loading: "Cargando...",
        empty: "No se encontraron categorias.",
        editTitle: "Editar categoria",
        save: "Guardar cambios",
        saving: "Guardando...",
        deleteTitle: "Eliminar categoria?",
        deleteDescription: (name: string) =>
          `Seguro que quieres eliminar "${name}"? Esta accion no se puede deshacer.`,
        deleted: "Categoria eliminada",
        created: "Categoria creada",
        updated: "Categoria actualizada",
        failedLoad: "No se pudieron cargar las categorias",
        failedCreate: "No se pudo crear la categoria",
        failedUpdate: "No se pudo actualizar la categoria",
        failedDelete: "No se pudo eliminar la categoria",
        ofTotal: (visible: number, total: number) => `(${visible} de ${total})`,
        validations: {
          nameRequired: "El nombre es obligatorio",
        },
      },
      transactions: {
        title: "Transacciones",
        subtitle: "Haz seguimiento de tus ingresos y gastos.",
        newCardTitle: "Nueva transaccion",
        newCardDescription: "Registra un ingreso o un gasto.",
        category: "Categoria",
        amount: "Monto",
        currency: "Moneda",
        dateTime: "Fecha y hora",
        descriptionOptional: "Descripcion (opcional)",
        categoryPlaceholder: "Selecciona categoria",
        amountPlaceholder: "Ej: 50000",
        currencyPlaceholder: "COP",
        create: "Crear transaccion",
        creating: "Creando...",
        filters: "Filtros",
        startDate: "Fecha inicial",
        endDate: "Fecha final",
        listTitle: "Transacciones",
        loading: "Cargando...",
        empty: "No se encontraron transacciones.",
        type: "Tipo",
        editTitle: "Editar transaccion",
        save: "Guardar cambios",
        saving: "Guardando...",
        deleteTitle: "Eliminar transaccion?",
        deleteDescription: (
          amount: string,
          currency: string,
          description?: string,
        ) =>
          `Seguro que quieres eliminar esta transaccion de ${amount} ${currency}${description ? ` - \"${description}\"` : ""}? Esta accion no se puede deshacer.`,
        created: "Transaccion creada",
        updated: "Transaccion actualizada",
        deleted: "Transaccion eliminada",
        failedLoad: "No se pudieron cargar las transacciones",
        failedCreate: "No se pudo crear la transaccion",
        failedUpdate: "No se pudo actualizar la transaccion",
        failedDelete: "No se pudo eliminar la transaccion",
        validations: {
          categoryRequired: "La categoria es obligatoria",
          amountRequired: "El monto es obligatorio",
          currencyRequired: "La moneda es obligatoria",
          dateRequired: "La fecha es obligatoria",
        },
      },
      profile: {
        title: "Perfil",
        subtitle: "Administra la informacion de tu cuenta.",
        preferencesTitle: "Preferencias",
        preferencesDescription:
          "Configura idioma y apariencia de la aplicacion.",
        languageLabel: "Idioma",
        appearanceLabel: "Apariencia",
        languageEs: "Espanol",
        languageEn: "Ingles",
        themeSystem: "Sistema",
        themeLight: "Claro",
        themeDark: "Oscuro",
        infoCardTitle: "Informacion de la cuenta",
        infoCardDescription:
          "Tu nombre se puede editar y se guarda automaticamente.",
        fullName: "Nombre completo",
        fullNamePlaceholder: "Tu nombre",
        email: "Correo",
        emailHint:
          "El correo se administra desde autenticacion y no se puede cambiar aqui.",
        memberSince: "Miembro desde",
        saving: "Guardando...",
        saved: "Guardado",
        dangerTitle: "Zona de peligro",
        dangerDescription:
          "Elimina permanentemente tu cuenta y todos los datos asociados.",
        deleteAccount: "Eliminar cuenta",
        confirmDeleteTitle: "Eliminar cuenta?",
        confirmDeleteDescription:
          "Esta accion es permanente. Tu perfil, transacciones y categorias se eliminaran y no se podran recuperar.",
        confirmDeleteButton: "Si, eliminar mi cuenta",
        deleting: "Eliminando...",
        deleted: "Cuenta eliminada",
        failedSaveName: "No se pudo guardar el nombre",
        failedDeleteAccount: "No se pudo eliminar la cuenta",
        dateLocale: "es-CO",
      },
    },
  },
  en: {
    metadata: {
      title: "Dinerance",
      description: "Dinerance Dashboard",
      htmlLang: "en",
    },
    common: {
      loading: "Loading...",
      unexpectedError: "Unexpected error",
      none: "None",
      all: "All",
      clearFilters: "Clear filters",
      refresh: "Refresh",
      cancel: "Cancel",
      saveChanges: "Save changes",
      edit: "Edit",
      delete: "Delete",
      actions: "Actions",
      direction: "Direction",
      category: "Category",
      date: "Date",
      amount: "Amount",
      currency: "Currency",
      description: "Description",
      dash: "-",
      income: "Income",
      expense: "Expense",
    },
    appLayout: {
      nav: {
        balance: "Balance",
        transactions: "Transactions",
        categories: "Categories",
        profile: "Profile",
      },
      signOut: "Sign out",
    },
    auth: {
      login: {
        title: "Sign in",
        email: "Email",
        password: "Password",
        submit: "Sign in",
        submitting: "Signing in...",
        noAccount: "Don't have an account?",
        register: "Register",
        notRegistered: "User is not registered.",
        validations: {
          invalidEmail: "Invalid email",
          passwordRequired: "Password required",
        },
        successToast: "Signed in successfully",
      },
      register: {
        title: "Create account",
        name: "Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm password",
        submit: "Create account",
        submitting: "Creating account...",
        hasAccount: "Already have an account?",
        signIn: "Sign in",
        validations: {
          nameRequired: "Name is required",
          invalidEmail: "Invalid email",
          passwordMin: "Password must be at least 8 characters",
          confirmRequired: "Please confirm your password",
          passwordsDontMatch: "Passwords don't match",
        },
        successToast: "Account created successfully.",
        profileCreatedToast: "User profile created successfully.",
      },
    },
    pages: {
      balance: {
        title: "Balance",
        subtitle: "Financial summary for the selected month and full history.",
        heading: (monthLabel: string) => `Financial summary - ${monthLabel}`,
        monthLabel: "Month",
        latestMonthHint:
          "Without a filter, the latest month with activity is shown.",
        currentCardDescription:
          "Consolidated view of income, expenses, and balance.",
        historyTitle: "Monthly balance",
        historyDescription: "Every month with recorded activity.",
        noHistory: "There is no activity yet to calculate the balance.",
        selectedMonthEmpty: "There is no activity in the selected month.",
      },
      categories: {
        title: "Categories",
        subtitle:
          "Organize your transactions by income and expense categories.",
        newCardTitle: "New category",
        newCardDescription: "Add a category to group your transactions.",
        name: "Name",
        direction: "Direction",
        parentOptional: "Parent (optional)",
        namePlaceholder: "e.g. Groceries",
        create: "Create category",
        creating: "Creating...",
        filters: "Filters",
        listTitle: "Categories",
        loading: "Loading...",
        empty: "No categories found.",
        editTitle: "Edit category",
        save: "Save changes",
        saving: "Saving...",
        deleteTitle: "Delete category?",
        deleteDescription: (name: string) =>
          `Are you sure you want to delete \"${name}\"? This action cannot be undone.`,
        deleted: "Category deleted",
        created: "Category created",
        updated: "Category updated",
        failedLoad: "Failed to load categories",
        failedCreate: "Failed to create category",
        failedUpdate: "Failed to update category",
        failedDelete: "Failed to delete category",
        ofTotal: (visible: number, total: number) => `(${visible} of ${total})`,
        validations: {
          nameRequired: "Name is required",
        },
      },
      transactions: {
        title: "Transactions",
        subtitle: "Track your income and expenses.",
        newCardTitle: "New transaction",
        newCardDescription: "Record a new income or expense.",
        category: "Category",
        amount: "Amount",
        currency: "Currency",
        dateTime: "Date & time",
        descriptionOptional: "Description (optional)",
        categoryPlaceholder: "Select category",
        amountPlaceholder: "e.g. 50000",
        currencyPlaceholder: "COP",
        create: "Create transaction",
        creating: "Creating...",
        filters: "Filters",
        startDate: "Start date",
        endDate: "End date",
        listTitle: "Transactions",
        loading: "Loading...",
        empty: "No transactions found.",
        type: "Type",
        editTitle: "Edit transaction",
        save: "Save changes",
        saving: "Saving...",
        deleteTitle: "Delete transaction?",
        deleteDescription: (
          amount: string,
          currency: string,
          description?: string,
        ) =>
          `Are you sure you want to delete this transaction of ${amount} ${currency}${description ? ` - \"${description}\"` : ""}? This action cannot be undone.`,
        created: "Transaction created",
        updated: "Transaction updated",
        deleted: "Transaction deleted",
        failedLoad: "Failed to load transactions",
        failedCreate: "Failed to create transaction",
        failedUpdate: "Failed to update transaction",
        failedDelete: "Failed to delete transaction",
        validations: {
          categoryRequired: "Category is required",
          amountRequired: "Amount is required",
          currencyRequired: "Currency is required",
          dateRequired: "Date is required",
        },
      },
      profile: {
        title: "Profile",
        subtitle: "Manage your account information.",
        preferencesTitle: "Preferences",
        preferencesDescription: "Configure app language and appearance.",
        languageLabel: "Language",
        appearanceLabel: "Appearance",
        languageEs: "Spanish",
        languageEn: "English",
        themeSystem: "System",
        themeLight: "Light",
        themeDark: "Dark",
        infoCardTitle: "Account information",
        infoCardDescription: "Your name is editable and saves automatically.",
        fullName: "Full name",
        fullNamePlaceholder: "Your name",
        email: "Email",
        emailHint:
          "Email is managed via authentication and cannot be changed here.",
        memberSince: "Member since",
        saving: "Saving...",
        saved: "Saved",
        dangerTitle: "Danger zone",
        dangerDescription:
          "Permanently delete your account and all associated data.",
        deleteAccount: "Delete account",
        confirmDeleteTitle: "Delete account?",
        confirmDeleteDescription:
          "This action is permanent. Your profile, transactions, and categories will be deleted and cannot be recovered.",
        confirmDeleteButton: "Yes, delete my account",
        deleting: "Deleting...",
        deleted: "Account deleted",
        failedSaveName: "Failed to save name",
        failedDeleteAccount: "Failed to delete account",
        dateLocale: "en-US",
      },
    },
  },
} as const;

export type SiteText = (typeof siteTexts)[SiteLocale];

export function getSiteText(locale: SiteLocale = defaultSiteLocale): SiteText {
  return siteTexts[locale] ?? siteTexts[defaultSiteLocale];
}
